spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring_batch
    username: root
    password: password
    driver-class-name: com.mysql.cj.jdbc.Driver
  batch:
    job:
      enabled: false